- hosts: web
  become: yes

  vars:
    github_pat: "{{ vault_github_pat }}"

  tasks:
    - name: Install packages
      apt:
        name:
          - python3-pip
          - nginx
          - git
        state: present
        update_cache: yes

    - name: Clone the server repository
      git:
        repo: "https://github.com/amfoss/proctoring-backend"
        dest: /opt/app

    - name: Install requirements
      pip:
        requirements: /opt/app/requirements.txt

    - name: Download .seb file
      get_url:
        url: "https://raw.githubusercontent.com/amfoss/proctoring-seb/main/config.seb"
        dest: /var/www/html/config.seb
        headers:
          Authorization: "token {{ github_pat }}"

    - name: Deploy systemd service file
      copy:
        src: /opt/app/proctoring-server.service
        dest: /etc/systemd/system/proctoring-server.service
      notify: restart proctoring service

    - name: Download nginx site config from GitHub
      get_url:
        url: "https://raw.githubusercontent.com/amfoss/proctoring-seb/main/nginx/proctoring.conf"
        dest: /etc/nginx/sites-available/proctoring
        headers:
          Authorization: "token {{ github_pat }}"
      notify: reload nginx

    - name: Enable nginx site
      file:
        src: /etc/nginx/sites-available/proctoring
        dest: /etc/nginx/sites-enabled/proctoring
        state: link
      notify: reload nginx

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: reload nginx

    - name: Start proctoring service
      systemd:
        name: proctoring-server
        enabled: yes
        state: restarted
        daemon_reload: yes

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

    - name: restart proctoring service
      systemd:
        name: proctoring-server
        daemon_reload: yes
        state: restarted